try:
    num = int(input("enter your number:"))
    print (num)
    expect ValueError as ex:
    print("Exception: ",ex) 